name: Sync Upstream

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout your repo with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/pigzillaaaaa/daddylive.git

      - name: Fetch upstream main branch
        run: git fetch upstream main

      - name: Preserve your workflows
        run: |
          mv .github/workflows ../workflows_backup

      - name: Checkout upstream files
        run: git checkout upstream/main -- .

      - name: Restore your workflows
        run: |
          rm -rf .github/workflows
          mv ../workflows_backup .github/workflows

      - name: Commit and push changes
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git add .
          git commit -m "Sync from upstream (excluding workflows)" || echo "No changes to commit"
          git push origin main || echo "Push failed, likely due to workflow permissions"
